### ISSUE TITLE
CLDrawTool Runtime Error

### ISSUE THREAD

**Issue by cliffjoyce** [yackle/CLImageEditor#195]
Xcode 9 reports a Runtime Error for line 338 of CLDrawTool.m buildImage method when run on actual iOS 11 device:

`UIGraphicsBeginImageContextWithOptions(_originalImageSize, NO, self.editor.imageView.image.scale);`

The error is "[UIImageView image] must be used from main thread only".

**Comment by yackle** [comment]
Fixed, thanks!

**Comment by hermannkuschke** [comment]
I still get this error! In addition, the same error occurs in all tools inside the buildImage func.

**Comment by Tippit** [comment]
Does this link could help ?

https://developer.apple.com/documentation/code_diagnostics/main_thread_checker

**Comment by yackle** [comment]
@hermannkuschke Did you use cocoapods? Please try v0.2.2
